### PR TITLE
RIUI-1794 bug fixed

### PR DESCRIPTION
**Pull request by dpanov76**

### CODE REVIEW

**Comment by matthewspeake-hmcts** [comment]
Yep all looks good.  @dpanov76 explained he's relying now on a frontend field as the backend field is no longer present (I think I recall that's consistent with a change Alan had to do when SSCS changed their config).

**Comment by matthewspeake-hmcts** [comment]
Also UTC dates now need to be formatted correctly - hence the piped dates.

**Comment by matthewspeake-hmcts** [comment]
Included files are not scoped to be tested.  At any rate - approved. Thanks @dpanov76

**Comment by Mo-Lala84** [comment]
Looks ok to me.  Thanks.

**Comment by Vamshi-Muniganti** [comment]
all tests passed

**Pull request merged**
